export const STRINGS = {
  GoogleSansBold: "GoogleSansBold",
  GoogleSansMedium: "GoogleSansMedium",
  GoogleSansRegular: "GoogleSansRegular",
  CedarvilleCursiveRegular: "CedarvilleCursiveRegular",
  edit: "Edit",
  errorMessage:
    "Something interrupted the process. Let’s try that one more time.",
  retry: "Retry",
  errorTitle: "Oops, That Didn’t Work",
  // commentUpdated: "your comment has been upgraded with premium freshness.",
  ok: "Ok",
  success: "Success",
  loginText1: "POST THE VIBES",
  loginText2: "can’t explain.",
  name: "Name",
  loginButtonText: "Welcome to YOU",
  you: "YOU",
  posts: "posts",
  email: "Email",
  postPublished: "Post published ✅",
  toastError: "Something went wrong ❌",
  commentUpdated: "Comment updated ✅",
  postDescPlaceholder: "write about YOU...",
  url: "https://jsonplaceholder.typicode.com",
  emailRegex: /^[^s@]+@[^s@]+.[^s@]+$/,
  loginDesc: "let YOU set things up for you.",
};
